#!/bin/bash

az group delete -y --no-wait -g west-ca-la-101
az group delete -y --no-wait -g west-ca-la-102
az group delete -y --no-wait -g west-ca-la-103
az group delete -y --no-wait -g west-ca-la-104
az group delete -y --no-wait -g west-ca-la-105
az group delete -y --no-wait -g west-ca-sfo-101
az group delete -y --no-wait -g west-ca-sfo-102
az group delete -y --no-wait -g west-ca-sfo-103
az group delete -y --no-wait -g west-ca-sfo-104
az group delete -y --no-wait -g west-ca-sfo-105
az group delete -y --no-wait -g west-ca-sd-101
az group delete -y --no-wait -g west-ca-sd-102
az group delete -y --no-wait -g west-ca-sd-103
az group delete -y --no-wait -g west-ca-sd-104
az group delete -y --no-wait -g west-ca-sd-105
az group delete -y --no-wait -g west-ca-sac-101
az group delete -y --no-wait -g west-ca-sac-102
az group delete -y --no-wait -g west-ca-sac-103
az group delete -y --no-wait -g west-ca-sac-104
az group delete -y --no-wait -g west-ca-sac-105
az group delete -y --no-wait -g west-ca-north-101
az group delete -y --no-wait -g west-ca-north-102
az group delete -y --no-wait -g west-ca-north-103
az group delete -y --no-wait -g west-ca-north-104
az group delete -y --no-wait -g west-ca-north-105
az group delete -y --no-wait -g west-ca-south-101
az group delete -y --no-wait -g west-ca-south-102
az group delete -y --no-wait -g west-ca-south-103
az group delete -y --no-wait -g west-ca-south-104
az group delete -y --no-wait -g west-ca-south-105
az group delete -y --no-wait -g west-ca-east-101
az group delete -y --no-wait -g west-ca-east-102
az group delete -y --no-wait -g west-ca-east-103
az group delete -y --no-wait -g west-ca-east-104
az group delete -y --no-wait -g west-ca-east-105
az group delete -y --no-wait -g west-ca-west-101
az group delete -y --no-wait -g west-ca-west-102
az group delete -y --no-wait -g west-ca-west-103
az group delete -y --no-wait -g west-ca-west-104
az group delete -y --no-wait -g west-ca-west-105
