#!/bin/bash

az group delete -y --no-wait -g central-tx-austin-101
az group delete -y --no-wait -g central-tx-austin-102
az group delete -y --no-wait -g central-tx-austin-103
az group delete -y --no-wait -g central-tx-austin-104
az group delete -y --no-wait -g central-tx-austin-105
az group delete -y --no-wait -g central-tx-dallas-101
az group delete -y --no-wait -g central-tx-dallas-102
az group delete -y --no-wait -g central-tx-dallas-103
az group delete -y --no-wait -g central-tx-dallas-104
az group delete -y --no-wait -g central-tx-dallas-105
az group delete -y --no-wait -g central-tx-houston-101
az group delete -y --no-wait -g central-tx-houston-102
az group delete -y --no-wait -g central-tx-houston-103
az group delete -y --no-wait -g central-tx-houston-104
az group delete -y --no-wait -g central-tx-houston-105
az group delete -y --no-wait -g central-tx-san-101
az group delete -y --no-wait -g central-tx-san-102
az group delete -y --no-wait -g central-tx-san-103
az group delete -y --no-wait -g central-tx-san-104
az group delete -y --no-wait -g central-tx-san-105
az group delete -y --no-wait -g central-tx-north-101
az group delete -y --no-wait -g central-tx-north-102
az group delete -y --no-wait -g central-tx-north-103
az group delete -y --no-wait -g central-tx-north-104
az group delete -y --no-wait -g central-tx-north-105
az group delete -y --no-wait -g central-tx-south-101
az group delete -y --no-wait -g central-tx-south-102
az group delete -y --no-wait -g central-tx-south-103
az group delete -y --no-wait -g central-tx-south-104
az group delete -y --no-wait -g central-tx-south-105
az group delete -y --no-wait -g central-tx-east-101
az group delete -y --no-wait -g central-tx-east-102
az group delete -y --no-wait -g central-tx-east-103
az group delete -y --no-wait -g central-tx-east-104
az group delete -y --no-wait -g central-tx-east-105
az group delete -y --no-wait -g central-tx-west-101
az group delete -y --no-wait -g central-tx-west-102
az group delete -y --no-wait -g central-tx-west-103
az group delete -y --no-wait -g central-tx-west-104
az group delete -y --no-wait -g central-tx-west-105
az group delete -y --no-wait -g central-mo-stlouis-101
az group delete -y --no-wait -g central-mo-stlouis-102
az group delete -y --no-wait -g central-mo-stlouis-103
az group delete -y --no-wait -g central-mo-stlouis-104
az group delete -y --no-wait -g central-mo-stlouis-105
az group delete -y --no-wait -g central-mo-kc-101
az group delete -y --no-wait -g central-mo-kc-102
az group delete -y --no-wait -g central-mo-kc-103
az group delete -y --no-wait -g central-mo-kc-104
az group delete -y --no-wait -g central-mo-kc-105
az group delete -y --no-wait -g central-mo-columbia-101
az group delete -y --no-wait -g central-mo-columbia-102
az group delete -y --no-wait -g central-mo-columbia-103
az group delete -y --no-wait -g central-mo-columbia-104
az group delete -y --no-wait -g central-mo-columbia-105
az group delete -y --no-wait -g central-mo-north-101
az group delete -y --no-wait -g central-mo-north-102
az group delete -y --no-wait -g central-mo-north-103
az group delete -y --no-wait -g central-mo-north-104
az group delete -y --no-wait -g central-mo-north-105
az group delete -y --no-wait -g central-mo-south-101
az group delete -y --no-wait -g central-mo-south-102
az group delete -y --no-wait -g central-mo-south-103
az group delete -y --no-wait -g central-mo-south-104
az group delete -y --no-wait -g central-mo-south-105
az group delete -y --no-wait -g central-mo-east-101
az group delete -y --no-wait -g central-mo-east-102
az group delete -y --no-wait -g central-mo-east-103
az group delete -y --no-wait -g central-mo-east-104
az group delete -y --no-wait -g central-mo-east-105
az group delete -y --no-wait -g central-mo-west-101
az group delete -y --no-wait -g central-mo-west-102
az group delete -y --no-wait -g central-mo-west-103
az group delete -y --no-wait -g central-mo-west-104
az group delete -y --no-wait -g central-mo-west-105
