#!/bin/bash

az group delete -y --no-wait -g east-ga-atlanta-101
az group delete -y --no-wait -g east-ga-atlanta-102
az group delete -y --no-wait -g east-ga-atlanta-103
az group delete -y --no-wait -g east-ga-atlanta-104
az group delete -y --no-wait -g east-ga-atlanta-105
az group delete -y --no-wait -g east-ga-athens-101
az group delete -y --no-wait -g east-ga-athens-102
az group delete -y --no-wait -g east-ga-athens-103
az group delete -y --no-wait -g east-ga-athens-104
az group delete -y --no-wait -g east-ga-athens-105
az group delete -y --no-wait -g east-ga-north-101
az group delete -y --no-wait -g east-ga-north-102
az group delete -y --no-wait -g east-ga-north-103
az group delete -y --no-wait -g east-ga-north-104
az group delete -y --no-wait -g east-ga-north-105
az group delete -y --no-wait -g east-ga-south-101
az group delete -y --no-wait -g east-ga-south-102
az group delete -y --no-wait -g east-ga-south-103
az group delete -y --no-wait -g east-ga-south-104
az group delete -y --no-wait -g east-ga-south-105
az group delete -y --no-wait -g east-nc-charlotte-101
az group delete -y --no-wait -g east-nc-charlotte-102
az group delete -y --no-wait -g east-nc-charlotte-103
az group delete -y --no-wait -g east-nc-charlotte-104
az group delete -y --no-wait -g east-nc-charlotte-105
az group delete -y --no-wait -g east-nc-raleigh-101
az group delete -y --no-wait -g east-nc-raleigh-102
az group delete -y --no-wait -g east-nc-raleigh-103
az group delete -y --no-wait -g east-nc-raleigh-104
az group delete -y --no-wait -g east-nc-raleigh-105
az group delete -y --no-wait -g east-nc-durham-101
az group delete -y --no-wait -g east-nc-durham-102
az group delete -y --no-wait -g east-nc-durham-103
az group delete -y --no-wait -g east-nc-durham-104
az group delete -y --no-wait -g east-nc-durham-105
az group delete -y --no-wait -g east-nc-east-101
az group delete -y --no-wait -g east-nc-east-102
az group delete -y --no-wait -g east-nc-east-103
az group delete -y --no-wait -g east-nc-east-104
az group delete -y --no-wait -g east-nc-east-105
az group delete -y --no-wait -g east-nc-west-101
az group delete -y --no-wait -g east-nc-west-102
az group delete -y --no-wait -g east-nc-west-103
az group delete -y --no-wait -g east-nc-west-104
az group delete -y --no-wait -g east-nc-west-105
