#!/bin/bash

az group delete -y --no-wait -g central-tx-austin-101
az group delete -y --no-wait -g central-tx-austin-102
az group delete -y --no-wait -g central-tx-austin-103
az group delete -y --no-wait -g central-tx-austin-104
az group delete -y --no-wait -g central-tx-austin-105
az group delete -y --no-wait -g central-tx-dallas-101
az group delete -y --no-wait -g central-tx-dallas-102
az group delete -y --no-wait -g central-tx-dallas-103
az group delete -y --no-wait -g central-tx-dallas-104
az group delete -y --no-wait -g central-tx-dallas-105
az group delete -y --no-wait -g central-tx-houston-101
az group delete -y --no-wait -g central-tx-houston-102
az group delete -y --no-wait -g central-tx-houston-103
az group delete -y --no-wait -g central-tx-houston-104
az group delete -y --no-wait -g central-tx-houston-105
az group delete -y --no-wait -g central-tx-san-101
az group delete -y --no-wait -g central-tx-san-102
az group delete -y --no-wait -g central-tx-san-103
az group delete -y --no-wait -g central-tx-san-104
az group delete -y --no-wait -g central-tx-san-105
az group delete -y --no-wait -g central-tx-north-101
az group delete -y --no-wait -g central-tx-north-102
az group delete -y --no-wait -g central-tx-north-103
az group delete -y --no-wait -g central-tx-north-104
az group delete -y --no-wait -g central-tx-north-105
az group delete -y --no-wait -g central-tx-south-101
az group delete -y --no-wait -g central-tx-south-102
az group delete -y --no-wait -g central-tx-south-103
az group delete -y --no-wait -g central-tx-south-104
az group delete -y --no-wait -g central-tx-south-105
az group delete -y --no-wait -g central-tx-east-101
az group delete -y --no-wait -g central-tx-east-102
az group delete -y --no-wait -g central-tx-east-103
az group delete -y --no-wait -g central-tx-east-104
az group delete -y --no-wait -g central-tx-east-105
az group delete -y --no-wait -g central-tx-west-101
az group delete -y --no-wait -g central-tx-west-102
az group delete -y --no-wait -g central-tx-west-103
az group delete -y --no-wait -g central-tx-west-104
az group delete -y --no-wait -g central-tx-west-105
