#!/bin/bash

cd ..

./create-cluster.sh east ga atlanta 101 &
./create-cluster.sh east ga atlanta 102 &
./create-cluster.sh east ga atlanta 103 &
./create-cluster.sh east ga atlanta 104 &
./create-cluster.sh east ga atlanta 105 &
./create-cluster.sh east ga athens 101 &
./create-cluster.sh east ga athens 102 &
./create-cluster.sh east ga athens 103 &
./create-cluster.sh east ga athens 104 &
./create-cluster.sh east ga athens 105 &
./create-cluster.sh east ga north 101 &
./create-cluster.sh east ga north 102 &
./create-cluster.sh east ga north 103 &
./create-cluster.sh east ga north 104 &
./create-cluster.sh east ga north 105 &
./create-cluster.sh east ga south 101 &
./create-cluster.sh east ga south 102 &
./create-cluster.sh east ga south 103 &
./create-cluster.sh east ga south 104 &
./create-cluster.sh east ga south 105 &
./create-cluster.sh east nc charlotte 101 &
./create-cluster.sh east nc charlotte 102 &
./create-cluster.sh east nc charlotte 103 &
./create-cluster.sh east nc charlotte 104 &
./create-cluster.sh east nc charlotte 105 &
./create-cluster.sh east nc raleigh 101 &
./create-cluster.sh east nc raleigh 102 &
./create-cluster.sh east nc raleigh 103 &
./create-cluster.sh east nc raleigh 104 &
./create-cluster.sh east nc raleigh 105 &
./create-cluster.sh east nc durham 101 &
./create-cluster.sh east nc durham 102 &
./create-cluster.sh east nc durham 103 &
./create-cluster.sh east nc durham 104 &
./create-cluster.sh east nc durham 105 &
./create-cluster.sh east nc east 101 &
./create-cluster.sh east nc east 102 &
./create-cluster.sh east nc east 103 &
./create-cluster.sh east nc east 104 &
./create-cluster.sh east nc east 105 &
./create-cluster.sh east nc west 101 &
./create-cluster.sh east nc west 102 &
./create-cluster.sh east nc west 103 &
./create-cluster.sh east nc west 104 &
./create-cluster.sh east nc west 105 &
