#!/bin/bash

cd ..

./create-cluster.sh west ca la 101 &
./create-cluster.sh west ca la 102 &
./create-cluster.sh west ca la 103 &
./create-cluster.sh west ca la 104 &
./create-cluster.sh west ca la 105 &
./create-cluster.sh west ca sfo 101 &
./create-cluster.sh west ca sfo 102 &
./create-cluster.sh west ca sfo 103 &
./create-cluster.sh west ca sfo 104 &
./create-cluster.sh west ca sfo 105 &
./create-cluster.sh west ca sd 101 &
./create-cluster.sh west ca sd 102 &
./create-cluster.sh west ca sd 103 &
./create-cluster.sh west ca sd 104 &
./create-cluster.sh west ca sd 105 &
./create-cluster.sh west ca sac 101 &
./create-cluster.sh west ca sac 102 &
./create-cluster.sh west ca sac 103 &
./create-cluster.sh west ca sac 104 &
./create-cluster.sh west ca sac 105 &
./create-cluster.sh west ca north 101 &
./create-cluster.sh west ca north 102 &
./create-cluster.sh west ca north 103 &
./create-cluster.sh west ca north 104 &
./create-cluster.sh west ca north 105 &
./create-cluster.sh west ca south 101 &
./create-cluster.sh west ca south 102 &
./create-cluster.sh west ca south 103 &
./create-cluster.sh west ca south 104 &
./create-cluster.sh west ca south 105 &
./create-cluster.sh west ca east 101 &
./create-cluster.sh west ca east 102 &
./create-cluster.sh west ca east 103 &
./create-cluster.sh west ca east 104 &
./create-cluster.sh west ca east 105 &
./create-cluster.sh west ca west 101 &
./create-cluster.sh west ca west 102 &
./create-cluster.sh west ca west 103 &
./create-cluster.sh west ca west 104 &
./create-cluster.sh west ca west 105 &
./create-cluster.sh west wa seattle 101 &
./create-cluster.sh west wa seattle 102 &
./create-cluster.sh west wa seattle 103 &
./create-cluster.sh west wa seattle 104 &
./create-cluster.sh west wa seattle 105 &
./create-cluster.sh west wa spokane 101 &
./create-cluster.sh west wa spokane 102 &
./create-cluster.sh west wa spokane 103 &
./create-cluster.sh west wa spokane 104 &
./create-cluster.sh west wa spokane 105 &
./create-cluster.sh west wa olympia 101 &
./create-cluster.sh west wa olympia 102 &
./create-cluster.sh west wa olympia 103 &
./create-cluster.sh west wa olympia 104 &
./create-cluster.sh west wa olympia 105 &
./create-cluster.sh west wa west 101 &
./create-cluster.sh west wa west 102 &
./create-cluster.sh west wa west 103 &
./create-cluster.sh west wa west 104 &
./create-cluster.sh west wa west 105 &
./create-cluster.sh west wa central 101 &
./create-cluster.sh west wa central 102 &
./create-cluster.sh west wa central 103 &
./create-cluster.sh west wa central 104 &
./create-cluster.sh west wa central 105 &
./create-cluster.sh west wa east 101 &
./create-cluster.sh west wa east 102 &
./create-cluster.sh west wa east 103 &
./create-cluster.sh west wa east 104 &
./create-cluster.sh west wa east 105 &
